#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Luis Solorzano Mohammed Al-Marri

int fireDone = 0;
int debrisDone = 0;
int survivorDone = 0;
int emptyDone = 0;
int allDone = 0;

void stop()
{
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	sleep(1000);
}

void moveStraight(float dist)
{
	setMotorSpeed(motorB, 20);
	setMotorSpeed(motorC, 20);
	sleep(1750/40 * dist);
}

void leftTurn(int degree)
{
	resetGyro(gyroSensor);
	repeatUntil(getGyroDegrees(gyroSensor) <= -1 * degree)
	{
		setMotorSpeed(motorB, -10);
		setMotorSpeed(motorC,  10);
	}


}

void rightTurn(int degree)
{
	resetGyro(gyroSensor);
	repeatUntil(getGyroDegrees(gyroSensor) >= degree)
	{
		setMotorSpeed(motorB,  10);
		setMotorSpeed(motorC, -10);

	}
}

void fire ()
{
	while(getColorName(colorSensor) != colorYellow)
	{
		setMotorSpeed(motorB, 20);
		setMotorSpeed(motorC, 20);
	}
	stop();

	if (getColorName(colorSensor) == colorYellow)
	{
		displayTextLine(1, "Firefighting");
		sleep(4000);
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
	}

	rightTurn(40);
	moveStraight(30);
	rightTurn(40);
}

void armRaise ()
{
	while (getUSDistance(S4) > 15)
	{
	setMotorSpeed(motorB, 20);
	setMotorSpeed(motorC, 20);
	}
	stop();
	setMotorSpeed(motorA, -10);
	sleep(1000);
	setMotorSpeed(motorB, 10);
	setMotorSpeed(motorC, 10);
	sleep(1500);
	stop();
	setMotorSpeed(motorA, 10);
	sleep(5000);
}

void empty()
{
		moveStraight(50);
		stop();
		displayTextLine(1, "Searching");
		sleep(3000);
		rightTurn(80);
}

void debris()
{
	while(getUSDistance(sonarSensor) > 10)
	{
		setMotorSpeed(motorB, 20);
		setMotorSpeed(motorC, 20);
	}
		stop();
		rightTurn(40);
		moveStraight(60);
		rightTurn(45);
}

task main()
{
	debris();
	empty();
	fire();
	armRaise();
}
